import os

catchphrases = [

    "I'll have what she's having",
    "If You Don't Know, Now You Know",
    "Yep, Yep, Yep. What It Do.",
    "Believe you me." ,
    "You are the Weakest Link! Goodbye!",
    "What a gay day!",
    "Absolute filth . . . and I LOVED it!",
    "A real bobby-dazzler",
    "And that's the way it is.",
    "Bazoopers!",
    "Did I do that?",
    "Don't make me angry",
    "I love it when a plan comes together",
    "[Insert name], you ignorant slut",
    "Make it so",
    "Now cut that out!",
    "The truth is out there",
    "Yada, yada, yada",
    "Why so serious?",
    "Here's looking at you, kid",
    "I have a bad feeling about this",
    "Woo woo woo you know it!",
    "You better recognize!",
    "I don't know, dawg",
    "Welcome to flavortown!",
    "You're Already Dead",
    "In The Name Of The Moon, I Will Punish You!",
    "I Don't Know Everything, I Just Know What I Know",
    "I'm All Fired Up!",
    "Believe It!",
    "KA-ME-HA-ME-HA!",
    "You can't say that on TV",
    "Go, Go, Gadget [Insert item]!",
    "Well, isn't that special?",
    "The tribe has spoken",
    "Homey don't play that!",
    "Good night, and good luck",
    "It's showtime!",
    "Alrighty then!",
    "Well, la-de-da.",
    "Dammit, man, I'm a DOCTOR, not a [Insert profession]",
    "There can be only one.",
    "Time to nut up or shut up.",
    "I'm too old for this shit.",
    "I feel the need... the need for speed.",
    "Here's lookin' at you, kid.",
    "Sounds like SOMEBODY'S got a case of the Mondays!",
    "Pay no attention to that man behind the curtain!",
    "That'll do, Pig.",
    "Oh yes I did!",
    "Well, Excuuuuuuse you!",
    "Bum, bum, bum...another one bites the dust!",
    "Well that's entropy for you",
    "Well excuse me princess!"
]

print catchphrases
