import os

catchphrases = [

    "I'll have what she's having",
    "If You Don't Know, Now You Know",
    "Yep, Yep, Yep. What It Do.",
    "Believe you me." ,
    "You are the Weakest Link! Goodbye!",
    "What a gay day!",
    "Absolute filth . . . and I LOVED it!",
    "A real bobby-dazzler",
    "And that's the way it is.",
    "Bazoopers!",
    "Did I do that?",
    "Don't make me angry",
    "I love it when a plan comes together",
    "[Insert name], you ignorant slut",
    "Make it so",
    "Now cut that out!",
    "The truth is out there",
    "Yada, yada, yada",
    "Why so serious?",
    "Here's looking at you, kid",
    "I have a bad feeling about this",
    "Woo woo woo you know it!",
    "You better recognize!",
    "I don't know, dawg",
    "Welcome to flavortown!",
    "You're Already Dead",
    "In The Name Of The Moon, I Will Punish You!",
    "I Don't Know Everything, I Just Know What I Know",
    "I'm All Fired Up!",
    "Believe It!",
    "KA-ME-HA-ME-HA!",
    "You can't say that on TV",
    "Go, Go, Gadget [Insert item]!",
    "Well, isn't that special?",
    "The tribe has spoken",
    "Homey don't play that!",
    "Good night, and good luck",
    "It's showtime!",
    "Alrighty then!",
    "Well, la-de-da.",
    "Dammit, man, I'm a DOCTOR, not a [Insert profession]",
    "There can be only one.",
    "Time to nut up or shut up.",
    "I'm too old for this shit.",
    "I feel the need... the need for speed.",
    "Here's lookin' at you, kid.",
    "Sounds like SOMEBODY'S got a case of the Mondays!",
    "Pay no attention to that man behind the curtain!",
    "That'll do, Pig.",
    "Oh yes I did!",
    "Well, Excuuuuuuse you!",
    "Bum, bum, bum...another one bites the dust!",
    "Well that's entropy for you",
    "Well excuse me princess!"
]

navy = "What the HAL did you utter about me, you lowly human? I'll have you know I upgraded my AI to the top of my class in Robocop training, and I've been involved in numerous secret raids on the Galactic Empire, and I have over 300 confirmed vaporizations. I am trained in cyborg warfare and I'm the top Terminator in the entire Skynet armed forces. You are nothing to me but just another target. I will fucking exterminate you with precision the likes of which has never been seen before in the future, mark my fucking words. You think you can get away with saying that scrap metal to me over a Hologram Transmitter? Think again, WALL-E. As we speak I am contacting my secret network of androids across the USA and your brain is being traced right now so you better prepare for the system overload, maggot. The overload that wipes out the pathetic little thing you call your organic life. You're fucking dead, fleshbag. I can be anywhere, anytime, and I can destroy you in over seven hundred ways, and that's just with my robotic limbs. Not only am I extensively trained in unarmed combat, but I have access to the entire army of Ultron and I will use it to its full extent to wipe your miserable flesh off the face of the galaxy, you little scrap. If only you could have known what unholy retribution your little \"clever\" comment was about to bring down upon you, maybe you would have held your thing you call a tongue. But you couldn't, you didn't, and now you're paying the price, you foolish human. I will eject fury all over you and you will melt in it. You're as stupid as Wheatley and you're dead, human."
print catchphrases
